<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\AirportsAtCitiesLookup;

use Ammonkc\SabreApi\AbstractModel;

class AirportsAtCitiesLookupResponseRailStationsItem extends AbstractModel
{
    /**
     * Returns the 3-letter other code.
    Repeats for every other code that is associated with the MAC code in the request.

     *
     * @var string
     */
    protected $code;
    /**
     * Name that corresponds to the other code.
     *
     * @var string
     */
    protected $name;

    /**
     * Returns the 3-letter other code.
    Repeats for every other code that is associated with the MAC code in the request.

     *
     * @return string
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Returns the 3-letter other code.
    Repeats for every other code that is associated with the MAC code in the request.

     *
     * @param string $code
     *
     * @return self
     */
    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Name that corresponds to the other code.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name that corresponds to the other code.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
