<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax;

class OrgOpentravelOta200305StreetNmbrType
{
    /**
     * Defines a Post Office Box number.
     *
     * @var string
     */
    protected $pOBox;
    /**
     * @var string
     */
    protected $content;

    /**
     * Defines a Post Office Box number.
     *
     * @return string
     */
    public function getPOBox(): ?string
    {
        return $this->pOBox;
    }

    /**
     * Defines a Post Office Box number.
     *
     * @param string $pOBox
     *
     * @return self
     */
    public function setPOBox(?string $pOBox): self
    {
        $this->pOBox = $pOBox;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     *
     * @return self
     */
    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }
}
