<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax;

use Ammonkc\SabreApi\AbstractModel;

class OrgOpentravelOta200305DiversityControlTypeDimensionsTimeOfDayDistribution extends AbstractModel
{
    /**
     * @var string
     */
    protected $direction;
    /**
     * @var string
     */
    protected $endpoint;
    /**
     * @var int
     */
    protected $leg;
    /**
     * @var OrgOpentravelOta200305DiversityControlTypeDimensionsTimeOfDayDistributionRange[]
     */
    protected $range;

    /**
     * @return string|null
     */
    public function getDirection(): ?string
    {
        return $this->direction;
    }

    /**
     * @param string|null $direction
     *
     * @return self
     */
    public function setDirection(?string $direction): self
    {
        $this->direction = $direction;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEndpoint(): ?string
    {
        return $this->endpoint;
    }

    /**
     * @param string|null $endpoint
     *
     * @return self
     */
    public function setEndpoint(?string $endpoint): self
    {
        $this->endpoint = $endpoint;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getLeg(): ?int
    {
        return $this->leg;
    }

    /**
     * @param int|null $leg
     *
     * @return self
     */
    public function setLeg(?int $leg): self
    {
        $this->leg = $leg;

        return $this;
    }

    /**
     * @return OrgOpentravelOta200305DiversityControlTypeDimensionsTimeOfDayDistributionRange[]|null
     */
    public function getRange(): ?array
    {
        return $this->range;
    }

    /**
     * @param OrgOpentravelOta200305DiversityControlTypeDimensionsTimeOfDayDistributionRange[]|null $range
     *
     * @return self
     */
    public function setRange(?array $range): self
    {
        $this->range = $range;

        return $this;
    }
}
