<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax;

class OrgOpentravelOta200305JumpCabinLogicType
{
    /**
     * Controls if response could contain options with cabin class different than requested.
     *
     * @var bool
     */
    protected $disabled;

    /**
     * Controls if response could contain options with cabin class different than requested.
     *
     * @return bool
     */
    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    /**
     * Controls if response could contain options with cabin class different than requested.
     *
     * @param bool $disabled
     *
     * @return self
     */
    public function setDisabled(?bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }
}
