<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax;

use Ammonkc\SabreApi\AbstractModel;

class PenaltiesType extends AbstractModel
{
    /**
     * @var Penalty[]
     */
    protected $penalties;

    /**
     * @return Penalty[]|null
     */
    public function getPenalties(): ?array
    {
        return $this->penalties;
    }

    /**
     * @param Penalty[]|null $penalties
     *
     * @return self
     */
    public function setPenalties(?array $penalties): self
    {
        $this->penalties = $penalties;

        return $this;
    }
}
