<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax;

class TaxSummaryIDType
{
    /**
     * Reference to TaxSummaryDesc ID.
     *
     * @var int
     */
    protected $ref;

    /**
     * Reference to TaxSummaryDesc ID.
     *
     * @return int
     */
    public function getRef(): ?int
    {
        return $this->ref;
    }

    /**
     * Reference to TaxSummaryDesc ID.
     *
     * @param int $ref
     *
     * @return self
     */
    public function setRef(?int $ref): self
    {
        $this->ref = $ref;

        return $this;
    }
}
