<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class HigherIntermediatePointTypeNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\HigherIntermediatePointType';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\HigherIntermediatePointType';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Ammonkc\SabreApi\Model\BargainFinderMax\HigherIntermediatePointType();
        if (property_exists($data, 'amount')) {
            $object->setAmount($data->{'amount'});
        }
        if (property_exists($data, 'cabinHigh')) {
            $object->setCabinHigh($data->{'cabinHigh'});
        }
        if (property_exists($data, 'cabinLow')) {
            $object->setCabinLow($data->{'cabinLow'});
        }
        if (property_exists($data, 'destination')) {
            $object->setDestination($data->{'destination'});
        }
        if (property_exists($data, 'fareClassHigh')) {
            $object->setFareClassHigh($data->{'fareClassHigh'});
        }
        if (property_exists($data, 'fareClassLow')) {
            $object->setFareClassLow($data->{'fareClassLow'});
        }
        if (property_exists($data, 'highDestination')) {
            $object->setHighDestination($data->{'highDestination'});
        }
        if (property_exists($data, 'highOrigin')) {
            $object->setHighOrigin($data->{'highOrigin'});
        }
        if (property_exists($data, 'lowDestination')) {
            $object->setLowDestination($data->{'lowDestination'});
        }
        if (property_exists($data, 'lowOrigin')) {
            $object->setLowOrigin($data->{'lowOrigin'});
        }
        if (property_exists($data, 'mileageSurchargePercentage')) {
            $object->setMileageSurchargePercentage($data->{'mileageSurchargePercentage'});
        }
        if (property_exists($data, 'origin')) {
            $object->setOrigin($data->{'origin'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getAmount()) {
            $data->{'amount'} = $object->getAmount();
        }
        if (null !== $object->getCabinHigh()) {
            $data->{'cabinHigh'} = $object->getCabinHigh();
        }
        if (null !== $object->getCabinLow()) {
            $data->{'cabinLow'} = $object->getCabinLow();
        }
        if (null !== $object->getDestination()) {
            $data->{'destination'} = $object->getDestination();
        }
        if (null !== $object->getFareClassHigh()) {
            $data->{'fareClassHigh'} = $object->getFareClassHigh();
        }
        if (null !== $object->getFareClassLow()) {
            $data->{'fareClassLow'} = $object->getFareClassLow();
        }
        if (null !== $object->getHighDestination()) {
            $data->{'highDestination'} = $object->getHighDestination();
        }
        if (null !== $object->getHighOrigin()) {
            $data->{'highOrigin'} = $object->getHighOrigin();
        }
        if (null !== $object->getLowDestination()) {
            $data->{'lowDestination'} = $object->getLowDestination();
        }
        if (null !== $object->getLowOrigin()) {
            $data->{'lowOrigin'} = $object->getLowOrigin();
        }
        if (null !== $object->getMileageSurchargePercentage()) {
            $data->{'mileageSurchargePercentage'} = $object->getMileageSurchargePercentage();
        }
        if (null !== $object->getOrigin()) {
            $data->{'origin'} = $object->getOrigin();
        }

        return $data;
    }
}
