<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OrgOpentravelOta200305AdvResTicketingTypeNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305AdvResTicketingType';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305AdvResTicketingType';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Ammonkc\SabreApi\Model\BargainFinderMax\OrgOpentravelOta200305AdvResTicketingType();
        if (property_exists($data, 'AdvResInd')) {
            $object->setAdvResInd($data->{'AdvResInd'});
        }
        if (property_exists($data, 'AdvReservation')) {
            $object->setAdvReservation($this->denormalizer->denormalize($data->{'AdvReservation'}, 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305AdvResTicketingTypeAdvReservation', 'json', $context));
        }
        if (property_exists($data, 'AdvTicketing')) {
            $object->setAdvTicketing($this->denormalizer->denormalize($data->{'AdvTicketing'}, 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305AdvResTicketingTypeAdvTicketing', 'json', $context));
        }
        if (property_exists($data, 'AdvTicketingInd')) {
            $object->setAdvTicketingInd($data->{'AdvTicketingInd'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getAdvResInd()) {
            $data->{'AdvResInd'} = $object->getAdvResInd();
        }
        if (null !== $object->getAdvReservation()) {
            $data->{'AdvReservation'} = $this->normalizer->normalize($object->getAdvReservation(), 'json', $context);
        }
        if (null !== $object->getAdvTicketing()) {
            $data->{'AdvTicketing'} = $this->normalizer->normalize($object->getAdvTicketing(), 'json', $context);
        }
        if (null !== $object->getAdvTicketingInd()) {
            $data->{'AdvTicketingInd'} = $object->getAdvTicketingInd();
        }

        return $data;
    }
}
