<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax\Normalizer;

use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OrgOpentravelOta200305VoluntaryChangesTypePenaltyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305VoluntaryChangesTypePenalty';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\OrgOpentravelOta200305VoluntaryChangesTypePenalty';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            return null;
        }
        $object = new \Ammonkc\SabreApi\Model\BargainFinderMax\OrgOpentravelOta200305VoluntaryChangesTypePenalty();
        if (property_exists($data, 'Amount') && $data->{'Amount'} !== null) {
            $object->setAmount($data->{'Amount'});
        }
        if (property_exists($data, 'CurrencyCode') && $data->{'CurrencyCode'} !== null) {
            $object->setCurrencyCode($data->{'CurrencyCode'});
        }
        if (property_exists($data, 'DecimalPlaces') && $data->{'DecimalPlaces'} !== null) {
            $object->setDecimalPlaces($data->{'DecimalPlaces'});
        }
        if (property_exists($data, 'DepartureStatus') && $data->{'DepartureStatus'} !== null) {
            $object->setDepartureStatus($data->{'DepartureStatus'});
        }
        if (property_exists($data, 'PenaltyType') && $data->{'PenaltyType'} !== null) {
            $object->setPenaltyType($data->{'PenaltyType'});
        }
        if (property_exists($data, 'Percent') && $data->{'Percent'} !== null) {
            $object->setPercent($data->{'Percent'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getAmount()) {
            $data->{'Amount'} = $object->getAmount();
        }
        if (null !== $object->getCurrencyCode()) {
            $data->{'CurrencyCode'} = $object->getCurrencyCode();
        }
        if (null !== $object->getDecimalPlaces()) {
            $data->{'DecimalPlaces'} = $object->getDecimalPlaces();
        }
        if (null !== $object->getDepartureStatus()) {
            $data->{'DepartureStatus'} = $object->getDepartureStatus();
        }
        if (null !== $object->getPenaltyType()) {
            $data->{'PenaltyType'} = $object->getPenaltyType();
        }
        if (null !== $object->getPercent()) {
            $data->{'Percent'} = $object->getPercent();
        }

        return $data;
    }
}
