<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SegmentsTypeNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\SegmentsType';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\SegmentsType';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Ammonkc\SabreApi\Model\BargainFinderMax\SegmentsType();
        if (property_exists($data, 'segment')) {
            $object->setSegment($this->denormalizer->denormalize($data->{'segment'}, 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\FareSegmentType', 'json', $context));
        }
        if (property_exists($data, 'surface')) {
            $object->setSurface($this->denormalizer->denormalize($data->{'surface'}, 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\SurfaceType', 'json', $context));
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getSegment()) {
            $data->{'segment'} = $this->normalizer->normalize($object->getSegment(), 'json', $context);
        }
        if (null !== $object->getSurface()) {
            $data->{'surface'} = $this->normalizer->normalize($object->getSurface(), 'json', $context);
        }

        return $data;
    }
}
