<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\BargainFinderMax\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SoldOutScheduleNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\SoldOutSchedule';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Ammonkc\\SabreApi\\Model\\BargainFinderMax\\SoldOutSchedule';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Ammonkc\SabreApi\Model\BargainFinderMax\SoldOutSchedule();
        if (property_exists($data, 'brandName')) {
            $object->setBrandName($data->{'brandName'});
        }
        if (property_exists($data, 'code')) {
            $object->setCode($data->{'code'});
        }
        if (property_exists($data, 'programCode')) {
            $object->setProgramCode($data->{'programCode'});
        }
        if (property_exists($data, 'programDescription')) {
            $object->setProgramDescription($data->{'programDescription'});
        }
        if (property_exists($data, 'programId')) {
            $object->setProgramId($data->{'programId'});
        }
        if (property_exists($data, 'programSystemCode')) {
            $object->setProgramSystemCode($data->{'programSystemCode'});
        }
        if (property_exists($data, 'ref')) {
            $object->setRef($data->{'ref'});
        }
        if (property_exists($data, 'status')) {
            $object->setStatus($data->{'status'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getBrandName()) {
            $data->{'brandName'} = $object->getBrandName();
        }
        if (null !== $object->getCode()) {
            $data->{'code'} = $object->getCode();
        }
        if (null !== $object->getProgramCode()) {
            $data->{'programCode'} = $object->getProgramCode();
        }
        if (null !== $object->getProgramDescription()) {
            $data->{'programDescription'} = $object->getProgramDescription();
        }
        if (null !== $object->getProgramId()) {
            $data->{'programId'} = $object->getProgramId();
        }
        if (null !== $object->getProgramSystemCode()) {
            $data->{'programSystemCode'} = $object->getProgramSystemCode();
        }
        if (null !== $object->getRef()) {
            $data->{'ref'} = $object->getRef();
        }
        if (null !== $object->getStatus()) {
            $data->{'status'} = $object->getStatus();
        }

        return $data;
    }
}
