<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodesCodeItem extends AbstractModel
{
    /**
     * Country code.
     *
     * @var string
     */
    protected $content;
    /**
     * Country Code.
     *
     * @var string
     */
    protected $codeContext;

    /**
     * Country code.
     *
     * @return string
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Country code.
     *
     * @param string $content
     *
     * @return self
     */
    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Country Code.
     *
     * @return string
     */
    public function getCodeContext(): ?string
    {
        return $this->codeContext;
    }

    /**
     * Country Code.
     *
     * @param string $codeContext
     *
     * @return self
     */
    public function setCodeContext(?string $codeContext): self
    {
        $this->codeContext = $codeContext;

        return $this;
    }
}
