<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwo extends AbstractModel
{
    /**
     * 'ExtendedPayment' is used to pass the number of months by which to extend the payment.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwoExtendedPayment
     */
    protected $extendedPayment;
    /**
     * 'Type' is used to specify the miscellaneous payment type.
     *
     * @var string
     */
    protected $type;
    /**
     * Used to reference a line number from PNR FOP field.
     *
     * @var int
     */
    protected $reference;

    /**
     * 'ExtendedPayment' is used to pass the number of months by which to extend the payment.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwoExtendedPayment|null
     */
    public function getExtendedPayment(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwoExtendedPayment
    {
        return $this->extendedPayment;
    }

    /**
     * 'ExtendedPayment' is used to pass the number of months by which to extend the payment.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwoExtendedPayment|null $extendedPayment
     *
     * @return self
     */
    public function setExtendedPayment(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirPriceItemPriceRequestInformationOptionalQualifiersFOPQualifiersBSPTicketingMultipleMiscFOPFOPTwoExtendedPayment $extendedPayment): self
    {
        $this->extendedPayment = $extendedPayment;

        return $this;
    }

    /**
     * 'Type' is used to specify the miscellaneous payment type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * 'Type' is used to specify the miscellaneous payment type.
     *
     * @param string|null $type
     *
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Used to reference a line number from PNR FOP field.
     *
     * @return int|null
     */
    public function getReference(): ?int
    {
        return $this->reference;
    }

    /**
     * Used to reference a line number from PNR FOP field.
     *
     * @param int|null $reference
     *
     * @return self
     */
    public function setReference(?int $reference): self
    {
        $this->reference = $reference;

        return $this;
    }
}
