<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareCommission extends AbstractModel
{
    /**
     * The commission amount.
     *
     * @var string
     */
    protected $amount;
    /**
     * The commission cap amount indicator.
     *
     * @var string
     */
    protected $capAmountInd;
    /**
     * The commission percent.
     *
     * @var string
     */
    protected $percent;

    /**
     * The commission amount.
     *
     * @return string|null
     */
    public function getAmount(): ?string
    {
        return $this->amount;
    }

    /**
     * The commission amount.
     *
     * @param string|null $amount
     *
     * @return self
     */
    public function setAmount(?string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * The commission cap amount indicator.
     *
     * @return string|null
     */
    public function getCapAmountInd(): ?string
    {
        return $this->capAmountInd;
    }

    /**
     * The commission cap amount indicator.
     *
     * @param string|null $capAmountInd
     *
     * @return self
     */
    public function setCapAmountInd(?string $capAmountInd): self
    {
        $this->capAmountInd = $capAmountInd;

        return $this;
    }

    /**
     * The commission percent.
     *
     * @return string|null
     */
    public function getPercent(): ?string
    {
        return $this->percent;
    }

    /**
     * The commission percent.
     *
     * @param string|null $percent
     *
     * @return self
     */
    public function setPercent(?string $percent): self
    {
        $this->percent = $percent;

        return $this;
    }
}
