<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOS extends AbstractModel
{
    /**
     * Point of Sale details.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOSSource
     */
    protected $source;

    /**
     * Point of Sale details.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOSSource
     */
    public function getSource(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOSSource
    {
        return $this->source;
    }

    /**
     * Point of Sale details.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOSSource $source
     *
     * @return self
     */
    public function setSource(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirTaxPOSSource $source): self
    {
        $this->source = $source;

        return $this;
    }
}
