<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailPersonName extends AbstractModel
{
    /**
     * The name number.
     *
     * @var string
     */
    protected $nameNumber;

    /**
     * The name number.
     *
     * @return string|null
     */
    public function getNameNumber(): ?string
    {
        return $this->nameNumber;
    }

    /**
     * The name number.
     *
     * @param string|null $nameNumber
     *
     * @return self
     */
    public function setNameNumber(?string $nameNumber): self
    {
        $this->nameNumber = $nameNumber;

        return $this;
    }
}
