<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareWarningsWarningItem extends AbstractModel
{
    /**
     * Any free text.
     *
     * @var string
     */
    protected $shortText;

    /**
     * Any free text.
     *
     * @return string
     */
    public function getShortText(): ?string
    {
        return $this->shortText;
    }

    /**
     * Any free text.
     *
     * @param string $shortText
     *
     * @return self
     */
    public function setShortText(?string $shortText): self
    {
        $this->shortText = $shortText;

        return $this;
    }
}
