<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicket extends AbstractModel
{
    /**
     * PDF request.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF
     */
    protected $pDF;
    /**
     * Used to send an email notification containing a text-based copy of the eTicket.
     *
     * @var bool
     */
    protected $ind;

    /**
     * PDF request.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF
     */
    public function getPDF(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF
    {
        return $this->pDF;
    }

    /**
     * PDF request.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF $pDF
     *
     * @return self
     */
    public function setPDF(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF $pDF): self
    {
        $this->pDF = $pDF;

        return $this;
    }

    /**
     * Used to send an email notification containing a text-based copy of the eTicket.
     *
     * @return bool
     */
    public function getInd(): ?bool
    {
        return $this->ind;
    }

    /**
     * Used to send an email notification containing a text-based copy of the eTicket.
     *
     * @param bool $ind
     *
     * @return self
     */
    public function setInd(?bool $ind): self
    {
        $this->ind = $ind;

        return $this;
    }
}
