<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentPaymentCardPhone extends AbstractModel
{
    /**
     * The phone use type.
     *
     * @var string
     */
    protected $phoneUseType;
    /**
     * The phone country code.
     *
     * @var string
     */
    protected $phoneCountryCode;
    /**
     * The phone number.
     *
     * @var string
     */
    protected $phoneNumber;

    /**
     * The phone use type.
     *
     * @return string
     */
    public function getPhoneUseType(): string
    {
        return $this->phoneUseType;
    }

    /**
     * The phone use type.
     *
     * @param string $phoneUseType
     *
     * @return self
     */
    public function setPhoneUseType(string $phoneUseType): self
    {
        $this->phoneUseType = $phoneUseType;

        return $this;
    }

    /**
     * The phone country code.
     *
     * @return string
     */
    public function getPhoneCountryCode(): string
    {
        return $this->phoneCountryCode;
    }

    /**
     * The phone country code.
     *
     * @param string $phoneCountryCode
     *
     * @return self
     */
    public function setPhoneCountryCode(string $phoneCountryCode): self
    {
        $this->phoneCountryCode = $phoneCountryCode;

        return $this;
    }

    /**
     * The phone number.
     *
     * @return string
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * The phone number.
     *
     * @param string $phoneNumber
     *
     * @return self
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }
}
