<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure extends AbstractModel
{
    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @var string[]
     */
    protected $text;

    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @return string[]|null
     */
    public function getText(): ?array
    {
        return $this->text;
    }

    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @param string[]|null $text
     *
     * @return self
     */
    public function setText(?array $text): self
    {
        $this->text = $text;

        return $this;
    }
}
