<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfo extends AbstractModel
{
    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoNonUSDOTDisclosure
     */
    protected $nonUSDOTDisclosure;
    /**
     * Used to return US DOT baggage disclosure-related information.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure
     */
    protected $uSDOTDisclosure;

    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoNonUSDOTDisclosure
     */
    public function getNonUSDOTDisclosure(): CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoNonUSDOTDisclosure
    {
        return $this->nonUSDOTDisclosure;
    }

    /**
     * Used to return non-US DOT baggage disclosure-related information.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoNonUSDOTDisclosure $nonUSDOTDisclosure
     *
     * @return self
     */
    public function setNonUSDOTDisclosure(CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoNonUSDOTDisclosure $nonUSDOTDisclosure): self
    {
        $this->nonUSDOTDisclosure = $nonUSDOTDisclosure;

        return $this;
    }

    /**
     * Used to return US DOT baggage disclosure-related information.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure
     */
    public function getUSDOTDisclosure(): CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure
    {
        return $this->uSDOTDisclosure;
    }

    /**
     * Used to return US DOT baggage disclosure-related information.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure $uSDOTDisclosure
     *
     * @return self
     */
    public function setUSDOTDisclosure(CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemItinTotalFareBaggageInfoUSDOTDisclosure $uSDOTDisclosure): self
    {
        $this->uSDOTDisclosure = $uSDOTDisclosure;

        return $this;
    }
}
