<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem extends AbstractModel
{
    /**
     * The surcharge information.
     *
     * @var string
     */
    protected $content;
    /**
     * The surcharge indicator.
     *
     * @var string
     */
    protected $ind;
    /**
     * The surcharge type.
     *
     * @var string
     */
    protected $type;

    /**
     * The surcharge information.
     *
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * The surcharge information.
     *
     * @param string|null $content
     *
     * @return self
     */
    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * The surcharge indicator.
     *
     * @return string|null
     */
    public function getInd(): ?string
    {
        return $this->ind;
    }

    /**
     * The surcharge indicator.
     *
     * @param string|null $ind
     *
     * @return self
     */
    public function setInd(?string $ind): self
    {
        $this->ind = $ind;

        return $this;
    }

    /**
     * The surcharge type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * The surcharge type.
     *
     * @param string|null $type
     *
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
}
