<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQAirBookRetryRebook extends AbstractModel
{
    /**
     * 'Option' is used to specify if re-booking of segments is required when UC segment status is encountered in any of the segments which is being booked.
     *
     * @var bool
     */
    protected $option;

    /**
     * 'Option' is used to specify if re-booking of segments is required when UC segment status is encountered in any of the segments which is being booked.
     *
     * @return bool|null
     */
    public function getOption(): ?bool
    {
        return $this->option;
    }

    /**
     * 'Option' is used to specify if re-booking of segments is required when UC segment status is encountered in any of the segments which is being booked.
     *
     * @param bool|null $option
     *
     * @return self
     */
    public function setOption(?bool $option): self
    {
        $this->option = $option;

        return $this;
    }
}
