<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItem extends AbstractModel
{
    /**
     * The branded fare details.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
     */
    protected $brandedFareInformation;
    /**
     * The cabin code.
     *
     * @var string
     */
    protected $cabin;
    /**
     * The fare basis details.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
     */
    protected $fareBasis;
    /**
     * The free baggage allowance information.
     *
     * @var string
     */
    protected $freeBaggageAllowance;
    /**
     * The surcharge information.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[]
     */
    protected $surcharges;

    /**
     * The branded fare details.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
     */
    public function getBrandedFareInformation(): CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
    {
        return $this->brandedFareInformation;
    }

    /**
     * The branded fare details.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation $brandedFareInformation
     *
     * @return self
     */
    public function setBrandedFareInformation(CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation $brandedFareInformation): self
    {
        $this->brandedFareInformation = $brandedFareInformation;

        return $this;
    }

    /**
     * The cabin code.
     *
     * @return string
     */
    public function getCabin(): string
    {
        return $this->cabin;
    }

    /**
     * The cabin code.
     *
     * @param string $cabin
     *
     * @return self
     */
    public function setCabin(string $cabin): self
    {
        $this->cabin = $cabin;

        return $this;
    }

    /**
     * The fare basis details.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
     */
    public function getFareBasis(): CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
    {
        return $this->fareBasis;
    }

    /**
     * The fare basis details.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis $fareBasis
     *
     * @return self
     */
    public function setFareBasis(CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis $fareBasis): self
    {
        $this->fareBasis = $fareBasis;

        return $this;
    }

    /**
     * The free baggage allowance information.
     *
     * @return string
     */
    public function getFreeBaggageAllowance(): string
    {
        return $this->freeBaggageAllowance;
    }

    /**
     * The free baggage allowance information.
     *
     * @param string $freeBaggageAllowance
     *
     * @return self
     */
    public function setFreeBaggageAllowance(string $freeBaggageAllowance): self
    {
        $this->freeBaggageAllowance = $freeBaggageAllowance;

        return $this;
    }

    /**
     * The surcharge information.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[]
     */
    public function getSurcharges(): array
    {
        return $this->surcharges;
    }

    /**
     * The surcharge information.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[] $surcharges
     *
     * @return self
     */
    public function setSurcharges(array $surcharges): self
    {
        $this->surcharges = $surcharges;

        return $this;
    }
}
