<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfo extends AbstractModel
{
    /**
     * Used to pass passenger contact numbers.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoContactNumbers
     */
    protected $contactNumbers;
    /**
     * Used to pass corporate ID into the record if applicable. Cannot combine with any other qualifier.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCorporate
     */
    protected $corporate;
    /**
     * Used to pass the credit card billing information. Please note that .../BillingInformation and .../PreferredCustomer are mutually exclusive.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCreditCardData
     */
    protected $creditCardData;
    /**
     * Used to pass frequent flyer number information.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCustLoyaltyItem[]
     */
    protected $custLoyalty;
    /**
     * Used to add a customer number into the record if applicable. Please note that this qualifier is not applicable to Sabre Sonic Res-based clients.
     *
     * @var string
     */
    protected $customerIdentifier;
    /**
     * Used to pass e-mail details.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoEmailItem[]
     */
    protected $email;
    /**
     * Used to add passenger names.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoPersonNameItem[]
     */
    protected $personName;

    /**
     * Used to pass passenger contact numbers.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoContactNumbers
     */
    public function getContactNumbers(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoContactNumbers
    {
        return $this->contactNumbers;
    }

    /**
     * Used to pass passenger contact numbers.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoContactNumbers $contactNumbers
     *
     * @return self
     */
    public function setContactNumbers(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoContactNumbers $contactNumbers): self
    {
        $this->contactNumbers = $contactNumbers;

        return $this;
    }

    /**
     * Used to pass corporate ID into the record if applicable. Cannot combine with any other qualifier.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCorporate
     */
    public function getCorporate(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCorporate
    {
        return $this->corporate;
    }

    /**
     * Used to pass corporate ID into the record if applicable. Cannot combine with any other qualifier.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCorporate $corporate
     *
     * @return self
     */
    public function setCorporate(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCorporate $corporate): self
    {
        $this->corporate = $corporate;

        return $this;
    }

    /**
     * Used to pass the credit card billing information. Please note that .../BillingInformation and .../PreferredCustomer are mutually exclusive.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCreditCardData
     */
    public function getCreditCardData(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCreditCardData
    {
        return $this->creditCardData;
    }

    /**
     * Used to pass the credit card billing information. Please note that .../BillingInformation and .../PreferredCustomer are mutually exclusive.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCreditCardData $creditCardData
     *
     * @return self
     */
    public function setCreditCardData(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCreditCardData $creditCardData): self
    {
        $this->creditCardData = $creditCardData;

        return $this;
    }

    /**
     * Used to pass frequent flyer number information.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCustLoyaltyItem[]
     */
    public function getCustLoyalty(): ?array
    {
        return $this->custLoyalty;
    }

    /**
     * Used to pass frequent flyer number information.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoCustLoyaltyItem[] $custLoyalty
     *
     * @return self
     */
    public function setCustLoyalty(?array $custLoyalty): self
    {
        $this->custLoyalty = $custLoyalty;

        return $this;
    }

    /**
     * Used to add a customer number into the record if applicable. Please note that this qualifier is not applicable to Sabre Sonic Res-based clients.
     *
     * @return string
     */
    public function getCustomerIdentifier(): ?string
    {
        return $this->customerIdentifier;
    }

    /**
     * Used to add a customer number into the record if applicable. Please note that this qualifier is not applicable to Sabre Sonic Res-based clients.
     *
     * @param string $customerIdentifier
     *
     * @return self
     */
    public function setCustomerIdentifier(?string $customerIdentifier): self
    {
        $this->customerIdentifier = $customerIdentifier;

        return $this;
    }

    /**
     * Used to pass e-mail details.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoEmailItem[]
     */
    public function getEmail(): ?array
    {
        return $this->email;
    }

    /**
     * Used to pass e-mail details.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoEmailItem[] $email
     *
     * @return self
     */
    public function setEmail(?array $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Used to add passenger names.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoPersonNameItem[]
     */
    public function getPersonName(): ?array
    {
        return $this->personName;
    }

    /**
     * Used to add passenger names.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoCustomerInfoPersonNameItem[] $personName
     *
     * @return self
     */
    public function setPersonName(?array $personName): self
    {
        $this->personName = $personName;

        return $this;
    }
}
