<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItem extends AbstractModel
{
    /**
     * The personal details.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemPersonName
     */
    protected $personName;
    /**
     * Used to specify miscellaneous free text information.
     *
     * @var string
     */
    protected $text;
    /**
     * The airline vendor preferences.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemVendorPrefs
     */
    protected $vendorPrefs;
    /**
     * The segment number.
     * Used to specify an itinerary segment to associate the SSR to.
     * If SSR_Code="OSI" 'SegmentNumber' cannot be utilized.
     *
     * @var string
     */
    protected $segmentNumber;
    /**
     * The SSR code.
     * Used to specify an SSR code such as 'WCHR', 'WGML', etc.
     *
     * @var string
     */
    protected $sSRCode;

    /**
     * The personal details.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemPersonName
     */
    public function getPersonName(): CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemPersonName
    {
        return $this->personName;
    }

    /**
     * The personal details.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemPersonName $personName
     *
     * @return self
     */
    public function setPersonName(CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemPersonName $personName): self
    {
        $this->personName = $personName;

        return $this;
    }

    /**
     * Used to specify miscellaneous free text information.
     *
     * @return string
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Used to specify miscellaneous free text information.
     *
     * @param string $text
     *
     * @return self
     */
    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * The airline vendor preferences.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemVendorPrefs
     */
    public function getVendorPrefs(): CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemVendorPrefs
    {
        return $this->vendorPrefs;
    }

    /**
     * The airline vendor preferences.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemVendorPrefs $vendorPrefs
     *
     * @return self
     */
    public function setVendorPrefs(CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoServiceItemVendorPrefs $vendorPrefs): self
    {
        $this->vendorPrefs = $vendorPrefs;

        return $this;
    }

    /**
     * The segment number.
     * Used to specify an itinerary segment to associate the SSR to.
     * If SSR_Code="OSI" 'SegmentNumber' cannot be utilized.
     *
     * @return string
     */
    public function getSegmentNumber(): string
    {
        return $this->segmentNumber;
    }

    /**
     * The segment number.
     * Used to specify an itinerary segment to associate the SSR to.
     * If SSR_Code="OSI" 'SegmentNumber' cannot be utilized.
     *
     * @param string $segmentNumber
     *
     * @return self
     */
    public function setSegmentNumber(string $segmentNumber): self
    {
        $this->segmentNumber = $segmentNumber;

        return $this;
    }

    /**
     * The SSR code.
     * Used to specify an SSR code such as 'WCHR', 'WGML', etc.
     *
     * @return string
     */
    public function getSSRCode(): string
    {
        return $this->sSRCode;
    }

    /**
     * The SSR code.
     * Used to specify an SSR code such as 'WCHR', 'WGML', etc.
     *
     * @param string $sSRCode
     *
     * @return self
     */
    public function setSSRCode(string $sSRCode): self
    {
        $this->sSRCode = $sSRCode;

        return $this;
    }
}
