<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddress extends AbstractModel
{
    /**
     * Address line.
     *
     * @var string[]
     */
    protected $addressLine;
    /**
     * City Name.
     *
     * @var string
     */
    protected $cityName;
    /**
     * State or province code.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvince
     */
    protected $stateProvince;
    /**
     * State or province codes.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvinceCodes
     */
    protected $stateProvinceCodes;
    /**
     * Post code.
     *
     * @var string
     */
    protected $postCode;
    /**
     * Country Code.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountry
     */
    protected $country;
    /**
     * Country Codes.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodes
     */
    protected $countryCodes;

    /**
     * Address line.
     *
     * @return string[]
     */
    public function getAddressLine(): ?array
    {
        return $this->addressLine;
    }

    /**
     * Address line.
     *
     * @param string[] $addressLine
     *
     * @return self
     */
    public function setAddressLine(?array $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * City Name.
     *
     * @return string
     */
    public function getCityName(): ?string
    {
        return $this->cityName;
    }

    /**
     * City Name.
     *
     * @param string $cityName
     *
     * @return self
     */
    public function setCityName(?string $cityName): self
    {
        $this->cityName = $cityName;

        return $this;
    }

    /**
     * State or province code.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvince
     */
    public function getStateProvince(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvince
    {
        return $this->stateProvince;
    }

    /**
     * State or province code.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvince $stateProvince
     *
     * @return self
     */
    public function setStateProvince(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvince $stateProvince): self
    {
        $this->stateProvince = $stateProvince;

        return $this;
    }

    /**
     * State or province codes.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvinceCodes
     */
    public function getStateProvinceCodes(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvinceCodes
    {
        return $this->stateProvinceCodes;
    }

    /**
     * State or province codes.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvinceCodes $stateProvinceCodes
     *
     * @return self
     */
    public function setStateProvinceCodes(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressStateProvinceCodes $stateProvinceCodes): self
    {
        $this->stateProvinceCodes = $stateProvinceCodes;

        return $this;
    }

    /**
     * Post code.
     *
     * @return string
     */
    public function getPostCode(): ?string
    {
        return $this->postCode;
    }

    /**
     * Post code.
     *
     * @param string $postCode
     *
     * @return self
     */
    public function setPostCode(?string $postCode): self
    {
        $this->postCode = $postCode;

        return $this;
    }

    /**
     * Country Code.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountry
     */
    public function getCountry(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountry
    {
        return $this->country;
    }

    /**
     * Country Code.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountry $country
     *
     * @return self
     */
    public function setCountry(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountry $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Country Codes.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodes
     */
    public function getCountryCodes(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodes
    {
        return $this->countryCodes;
    }

    /**
     * Country Codes.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodes $countryCodes
     *
     * @return self
     */
    public function setCountryCodes(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookPaymentInformationFormOfPaymentAgencyAddressCountryCodes $countryCodes): self
    {
        $this->countryCodes = $countryCodes;

        return $this;
    }
}
