<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQPostProcessingEndTransactionEmailETicketPDF extends AbstractModel
{
    /**
     * Used to indicate whether to send an email notification containing a PDF-based copy of the electronic ticket.
     *
     * @var bool
     */
    protected $ind;

    /**
     * Used to indicate whether to send an email notification containing a PDF-based copy of the electronic ticket.
     *
     * @return bool|null
     */
    public function getInd(): ?bool
    {
        return $this->ind;
    }

    /**
     * Used to indicate whether to send an email notification containing a PDF-based copy of the electronic ticket.
     *
     * @param bool|null $ind
     *
     * @return self
     */
    public function setInd(?bool $ind): self
    {
        $this->ind = $ind;

        return $this;
    }
}
