<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBook extends AbstractModel
{
    /**
     * Air segments details.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBookOriginDestinationOption
     */
    protected $originDestinationOption;

    /**
     * Air segments details.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBookOriginDestinationOption
     */
    public function getOriginDestinationOption(): ?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBookOriginDestinationOption
    {
        return $this->originDestinationOption;
    }

    /**
     * Air segments details.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBookOriginDestinationOption $originDestinationOption
     *
     * @return self
     */
    public function setOriginDestinationOption(?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirBookOriginDestinationOption $originDestinationOption): self
    {
        $this->originDestinationOption = $originDestinationOption;

        return $this;
    }
}
