<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddress extends AbstractModel
{
    /**
     * agency address.
     *
     * @var string
     */
    protected $addressLine;
    /**
     * agency city name.
     *
     * @var string
     */
    protected $cityName;
    /**
     * agency country code.
     *
     * @var string
     */
    protected $countryCode;
    /**
     * agency postal code.
     *
     * @var string
     */
    protected $postalCode;
    /**
     * state details.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressStateCountyProv
     */
    protected $stateCountyProv;
    /**
     * street number.
     *
     * @var string
     */
    protected $streetNmbr;
    /**
     * Used to specify if the request is based upon a hosted or a non-hosted carrier.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressVendorPrefs
     */
    protected $vendorPrefs;

    /**
     * agency address.
     *
     * @return string
     */
    public function getAddressLine(): ?string
    {
        return $this->addressLine;
    }

    /**
     * agency address.
     *
     * @param string $addressLine
     *
     * @return self
     */
    public function setAddressLine(?string $addressLine): self
    {
        $this->addressLine = $addressLine;

        return $this;
    }

    /**
     * agency city name.
     *
     * @return string
     */
    public function getCityName(): ?string
    {
        return $this->cityName;
    }

    /**
     * agency city name.
     *
     * @param string $cityName
     *
     * @return self
     */
    public function setCityName(?string $cityName): self
    {
        $this->cityName = $cityName;

        return $this;
    }

    /**
     * agency country code.
     *
     * @return string
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * agency country code.
     *
     * @param string $countryCode
     *
     * @return self
     */
    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * agency postal code.
     *
     * @return string
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * agency postal code.
     *
     * @param string $postalCode
     *
     * @return self
     */
    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * state details.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressStateCountyProv
     */
    public function getStateCountyProv(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressStateCountyProv
    {
        return $this->stateCountyProv;
    }

    /**
     * state details.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressStateCountyProv $stateCountyProv
     *
     * @return self
     */
    public function setStateCountyProv(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressStateCountyProv $stateCountyProv): self
    {
        $this->stateCountyProv = $stateCountyProv;

        return $this;
    }

    /**
     * street number.
     *
     * @return string
     */
    public function getStreetNmbr(): ?string
    {
        return $this->streetNmbr;
    }

    /**
     * street number.
     *
     * @param string $streetNmbr
     *
     * @return self
     */
    public function setStreetNmbr(?string $streetNmbr): self
    {
        $this->streetNmbr = $streetNmbr;

        return $this;
    }

    /**
     * Used to specify if the request is based upon a hosted or a non-hosted carrier.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressVendorPrefs
     */
    public function getVendorPrefs(): ?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressVendorPrefs
    {
        return $this->vendorPrefs;
    }

    /**
     * Used to specify if the request is based upon a hosted or a non-hosted carrier.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressVendorPrefs $vendorPrefs
     *
     * @return self
     */
    public function setVendorPrefs(?CreatePassengerNameRecordRequestCreatePassengerNameRecordRQTravelItineraryAddInfoAgencyInfoAddressVendorPrefs $vendorPrefs): self
    {
        $this->vendorPrefs = $vendorPrefs;

        return $this;
    }
}
