<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfo extends AbstractModel
{
    /**
     * The form of payment remark.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFOPRemark
     */
    protected $fOPRemark;
    /**
     * Used for future queue placement remark.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFutureQueuePlaceRemark
     */
    protected $futureQueuePlaceRemark;
    /**
     * Used for multiple remark types.
     *
     * @var CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoRemarkItem[]
     */
    protected $remark;

    /**
     * The form of payment remark.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFOPRemark
     */
    public function getFOPRemark(): CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFOPRemark
    {
        return $this->fOPRemark;
    }

    /**
     * The form of payment remark.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFOPRemark $fOPRemark
     *
     * @return self
     */
    public function setFOPRemark(CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFOPRemark $fOPRemark): self
    {
        $this->fOPRemark = $fOPRemark;

        return $this;
    }

    /**
     * Used for future queue placement remark.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFutureQueuePlaceRemark
     */
    public function getFutureQueuePlaceRemark(): CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFutureQueuePlaceRemark
    {
        return $this->futureQueuePlaceRemark;
    }

    /**
     * Used for future queue placement remark.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFutureQueuePlaceRemark $futureQueuePlaceRemark
     *
     * @return self
     */
    public function setFutureQueuePlaceRemark(CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoFutureQueuePlaceRemark $futureQueuePlaceRemark): self
    {
        $this->futureQueuePlaceRemark = $futureQueuePlaceRemark;

        return $this;
    }

    /**
     * Used for multiple remark types.
     *
     * @return CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoRemarkItem[]
     */
    public function getRemark(): array
    {
        return $this->remark;
    }

    /**
     * Used for multiple remark types.
     *
     * @param CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoRemarkItem[] $remark
     *
     * @return self
     */
    public function setRemark(array $remark): self
    {
        $this->remark = $remark;

        return $this;
    }
}
