<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsSpecialServiceSpecialServiceInfoSecureFlightItemPersonName extends AbstractModel
{
    /**
     * First name.
     *
     * @var string
     */
    protected $givenName;
    /**
     * Surname.
     *
     * @var string
     */
    protected $surname;
    /**
     * "DateOfBirth" and "Gender" cannot combine with "RedressNumber" and "KnownTravelerNumber".
     *
     * @var string
     */
    protected $dateOfBirth;
    /**
     * Gender.
     *
     * @var string
     */
    protected $gender;
    /**
     * Name number: 1.1, 2.1. etc.
     *
     * @var string
     */
    protected $nameNumber;

    /**
     * First name.
     *
     * @return string
     */
    public function getGivenName(): ?string
    {
        return $this->givenName;
    }

    /**
     * First name.
     *
     * @param string $givenName
     *
     * @return self
     */
    public function setGivenName(?string $givenName): self
    {
        $this->givenName = $givenName;

        return $this;
    }

    /**
     * Surname.
     *
     * @return string
     */
    public function getSurname(): ?string
    {
        return $this->surname;
    }

    /**
     * Surname.
     *
     * @param string $surname
     *
     * @return self
     */
    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * "DateOfBirth" and "Gender" cannot combine with "RedressNumber" and "KnownTravelerNumber".
     *
     * @return string
     */
    public function getDateOfBirth(): ?string
    {
        return $this->dateOfBirth;
    }

    /**
     * "DateOfBirth" and "Gender" cannot combine with "RedressNumber" and "KnownTravelerNumber".
     *
     * @param string $dateOfBirth
     *
     * @return self
     */
    public function setDateOfBirth(?string $dateOfBirth): self
    {
        $this->dateOfBirth = $dateOfBirth;

        return $this;
    }

    /**
     * Gender.
     *
     * @return string
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * Gender.
     *
     * @param string $gender
     *
     * @return self
     */
    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Name number: 1.1, 2.1. etc.
     *
     * @return string
     */
    public function getNameNumber(): ?string
    {
        return $this->nameNumber;
    }

    /**
     * Name number: 1.1, 2.1. etc.
     *
     * @param string $nameNumber
     *
     * @return self
     */
    public function setNameNumber(?string $nameNumber): self
    {
        $this->nameNumber = $nameNumber;

        return $this;
    }
}
