<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQSpecialReqDetailsAddRemarkRemarkInfoRemarkItem extends AbstractModel
{
    /**
     * Used to specify remark-related text.
     *
     * @var string
     */
    protected $text;
    /**
     * Used to specify an alpha sorting character such as: "H".
     *
     * @var string
     */
    protected $code;
    /**
     * 'SegmentNumber' is used to specify the number of the segment that the remark refers to.
     *
     * @var string
     */
    protected $segmentNumber;
    /**
     * Used to specify the remark type.
     *
     * @var string
     */
    protected $type;

    /**
     * Used to specify remark-related text.
     *
     * @return string|null
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * Used to specify remark-related text.
     *
     * @param string|null $text
     *
     * @return self
     */
    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * Used to specify an alpha sorting character such as: "H".
     *
     * @return string|null
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Used to specify an alpha sorting character such as: "H".
     *
     * @param string|null $code
     *
     * @return self
     */
    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * 'SegmentNumber' is used to specify the number of the segment that the remark refers to.
     *
     * @return string|null
     */
    public function getSegmentNumber(): ?string
    {
        return $this->segmentNumber;
    }

    /**
     * 'SegmentNumber' is used to specify the number of the segment that the remark refers to.
     *
     * @param string|null $segmentNumber
     *
     * @return self
     */
    public function setSegmentNumber(?string $segmentNumber): self
    {
        $this->segmentNumber = $segmentNumber;

        return $this;
    }

    /**
     * Used to specify the remark type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Used to specify the remark type.
     *
     * @param string|null $type
     *
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
}
