<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord;

use Ammonkc\SabreApi\AbstractModel;

class CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItem extends AbstractModel
{
    /**
     * Branded Fare details.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
     */
    protected $brandedFareInformation;
    /**
     * Cabin.
     *
     * @var string
     */
    protected $cabin;
    /**
     * Fare basis details.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
     */
    protected $fareBasis;
    /**
     * Free baggage allowance information.
     *
     * @var string
     */
    protected $freeBaggageAllowance;
    /**
     * Surcharges information.
     *
     * @var CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[]
     */
    protected $surcharges;

    /**
     * Branded Fare details.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
     */
    public function getBrandedFareInformation(): ?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation
    {
        return $this->brandedFareInformation;
    }

    /**
     * Branded Fare details.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation $brandedFareInformation
     *
     * @return self
     */
    public function setBrandedFareInformation(?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemBrandedFareInformation $brandedFareInformation): self
    {
        $this->brandedFareInformation = $brandedFareInformation;

        return $this;
    }

    /**
     * Cabin.
     *
     * @return string
     */
    public function getCabin(): ?string
    {
        return $this->cabin;
    }

    /**
     * Cabin.
     *
     * @param string $cabin
     *
     * @return self
     */
    public function setCabin(?string $cabin): self
    {
        $this->cabin = $cabin;

        return $this;
    }

    /**
     * Fare basis details.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
     */
    public function getFareBasis(): ?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis
    {
        return $this->fareBasis;
    }

    /**
     * Fare basis details.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis $fareBasis
     *
     * @return self
     */
    public function setFareBasis(?CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemFareBasis $fareBasis): self
    {
        $this->fareBasis = $fareBasis;

        return $this;
    }

    /**
     * Free baggage allowance information.
     *
     * @return string
     */
    public function getFreeBaggageAllowance(): ?string
    {
        return $this->freeBaggageAllowance;
    }

    /**
     * Free baggage allowance information.
     *
     * @param string $freeBaggageAllowance
     *
     * @return self
     */
    public function setFreeBaggageAllowance(?string $freeBaggageAllowance): self
    {
        $this->freeBaggageAllowance = $freeBaggageAllowance;

        return $this;
    }

    /**
     * Surcharges information.
     *
     * @return CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[]
     */
    public function getSurcharges(): ?array
    {
        return $this->surcharges;
    }

    /**
     * Surcharges information.
     *
     * @param CreatePassengerNameRecordResponseCreatePassengerNameRecordRSAirPriceItemPriceQuotePricedItineraryAirItineraryPricingInfoItemPTCFareBreakdownItemSurchargesItem[] $surcharges
     *
     * @return self
     */
    public function setSurcharges(?array $surcharges): self
    {
        $this->surcharges = $surcharges;

        return $this;
    }
}
