<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\AirlineLookup\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers = [];
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new AirlinesLookupResponseNormalizer();
        $normalizers[] = new AirlinesLookupResponseAirlineInfoItemNormalizer();
        $normalizers[] = new CommonLinksItemNormalizer();

        return $normalizers;
    }
}
