<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\AirlineLookup;

use Ammonkc\SabreApi\AbstractModel;

class AirlinesLookupResponse extends AbstractModel
{
    /**
     * Repeats associated airline information.
     *
     * @var AirlinesLookupResponseAirlineInfoItem[]
     */
    protected $airlineInfo;
    /**
     * @var CommonLinksItem[]
     */
    protected $links;

    /**
     * Repeats associated airline information.
     *
     * @return AirlinesLookupResponseAirlineInfoItem[]
     */
    public function getAirlineInfo(): ?array
    {
        return $this->airlineInfo;
    }

    /**
     * Repeats associated airline information.
     *
     * @param AirlinesLookupResponseAirlineInfoItem[] $airlineInfo
     *
     * @return self
     */
    public function setAirlineInfo(?array $airlineInfo): self
    {
        $this->airlineInfo = $airlineInfo;

        return $this;
    }

    /**
     * @return CommonLinksItem[]
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * @param CommonLinksItem[] $links
     *
     * @return self
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }
}
