<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\CreatePassengerNameRecord\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookRoomsRoomItemGuestsGuestItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ammonkc\\SabreApi\\Model\\CreatePassengerNameRecord\\CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookRoomsRoomItemGuestsGuestItem';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Ammonkc\SabreApi\Model\CreatePassengerNameRecord\CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookRoomsRoomItemGuestsGuestItem;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Ammonkc\SabreApi\Model\CreatePassengerNameRecord\CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookRoomsRoomItemGuestsGuestItem();
        if (property_exists($data, 'Contact')) {
            $object->setContact($this->denormalizer->denormalize($data->{'Contact'}, 'Ammonkc\\SabreApi\\Model\\CreatePassengerNameRecord\\CreatePassengerNameRecordRequestCreatePassengerNameRecordRQHotelBookRoomsRoomItemGuestsGuestItemContact', 'json', $context));
        }
        if (property_exists($data, 'Type')) {
            $object->setType($data->{'Type'});
        }
        if (property_exists($data, 'Email')) {
            $object->setEmail($data->{'Email'});
        }
        if (property_exists($data, 'Age')) {
            $object->setAge($data->{'Age'});
        }
        if (property_exists($data, 'Index')) {
            $object->setIndex($data->{'Index'});
        }
        if (property_exists($data, 'LeadGuest')) {
            $object->setLeadGuest($data->{'LeadGuest'});
        }
        if (property_exists($data, 'FrequentFlyerNumber')) {
            $object->setFrequentFlyerNumber($data->{'FrequentFlyerNumber'});
        }
        if (property_exists($data, 'LoyaltyId')) {
            $object->setLoyaltyId($data->{'LoyaltyId'});
        }
        if (property_exists($data, 'Title')) {
            $object->setTitle($data->{'Title'});
        }
        if (property_exists($data, 'FirstName')) {
            $object->setFirstName($data->{'FirstName'});
        }
        if (property_exists($data, 'LastName')) {
            $object->setLastName($data->{'LastName'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getContact()) {
            $data->{'Contact'} = $this->normalizer->normalize($object->getContact(), 'json', $context);
        }
        if (null !== $object->getType()) {
            $data->{'Type'} = $object->getType();
        }
        if (null !== $object->getEmail()) {
            $data->{'Email'} = $object->getEmail();
        }
        if (null !== $object->getAge()) {
            $data->{'Age'} = $object->getAge();
        }
        if (null !== $object->getIndex()) {
            $data->{'Index'} = $object->getIndex();
        }
        if (null !== $object->getLeadGuest()) {
            $data->{'LeadGuest'} = $object->getLeadGuest();
        }
        if (null !== $object->getFrequentFlyerNumber()) {
            $data->{'FrequentFlyerNumber'} = $object->getFrequentFlyerNumber();
        }
        if (null !== $object->getLoyaltyId()) {
            $data->{'LoyaltyId'} = $object->getLoyaltyId();
        }
        if (null !== $object->getTitle()) {
            $data->{'Title'} = $object->getTitle();
        }
        if (null !== $object->getFirstName()) {
            $data->{'FirstName'} = $object->getFirstName();
        }
        if (null !== $object->getLastName()) {
            $data->{'LastName'} = $object->getLastName();
        }

        return $data;
    }
}
