<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\SeatMap\Model;

class SeatMapResponseEnhancedSeatMapRSSeatMapSummaryItemCabinItemCabinClass
{
    /**
     * @var string
     */
    protected $cabinType;
    /**
     * @var string
     */
    protected $rBD;
    /**
     * @var string[]
     */
    protected $marketingDescription;

    /**
     * @return string
     */
    public function getCabinType(): ?string
    {
        return $this->cabinType;
    }

    /**
     * @param string $cabinType
     *
     * @return self
     */
    public function setCabinType(?string $cabinType): self
    {
        $this->cabinType = $cabinType;

        return $this;
    }

    /**
     * @return string
     */
    public function getRBD(): ?string
    {
        return $this->rBD;
    }

    /**
     * @param string $rBD
     *
     * @return self
     */
    public function setRBD(?string $rBD): self
    {
        $this->rBD = $rBD;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getMarketingDescription(): ?array
    {
        return $this->marketingDescription;
    }

    /**
     * @param string[] $marketingDescription
     *
     * @return self
     */
    public function setMarketingDescription(?array $marketingDescription): self
    {
        $this->marketingDescription = $marketingDescription;

        return $this;
    }
}
