<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\SeatMap\Model;

class SeatMapRequestEnhancedSeatMapRQSeatMapQueryEnhancedFareAvailQualifiersItemFareBreakCriteria
{
    /**
     * @var string
     */
    protected $vendorCode;
    /**
     * Fare amount with decimal points.
     *
     * @var string
     */
    protected $fareAmount;
    /**
     * Atpco fare rule.
     *
     * @var string
     */
    protected $atpcoFareRule;
    /**
     * private tariff indicator.
     *
     * @var string
     */
    protected $privateTariffIndicatorInd;
    /**
     * Carrier code.
     *
     * @var string
     */
    protected $governingCarrier;
    /**
     * fare type bitmap.
     *
     * @var string
     */
    protected $fareTypeBitmap;
    /**
     * Fare type string.
     *
     * @var string
     */
    protected $fareType;
    /**
     * fare indicator.
     *
     * @var string
     */
    protected $fareIndicator;
    /**
     * Fare Component Identifier.
     *
     * @var string
     */
    protected $fareComponentID;
    /**
     * Aptco fare tariff.
     *
     * @var string
     */
    protected $atpcoFareTariff;
    /**
     * @var mixed
     */
    protected $extensionPointSummary;

    /**
     * @return string
     */
    public function getVendorCode(): ?string
    {
        return $this->vendorCode;
    }

    /**
     * @param string $vendorCode
     *
     * @return self
     */
    public function setVendorCode(?string $vendorCode): self
    {
        $this->vendorCode = $vendorCode;

        return $this;
    }

    /**
     * Fare amount with decimal points.
     *
     * @return string
     */
    public function getFareAmount(): ?string
    {
        return $this->fareAmount;
    }

    /**
     * Fare amount with decimal points.
     *
     * @param string $fareAmount
     *
     * @return self
     */
    public function setFareAmount(?string $fareAmount): self
    {
        $this->fareAmount = $fareAmount;

        return $this;
    }

    /**
     * Atpco fare rule.
     *
     * @return string
     */
    public function getAtpcoFareRule(): ?string
    {
        return $this->atpcoFareRule;
    }

    /**
     * Atpco fare rule.
     *
     * @param string $atpcoFareRule
     *
     * @return self
     */
    public function setAtpcoFareRule(?string $atpcoFareRule): self
    {
        $this->atpcoFareRule = $atpcoFareRule;

        return $this;
    }

    /**
     * private tariff indicator.
     *
     * @return string
     */
    public function getPrivateTariffIndicatorInd(): ?string
    {
        return $this->privateTariffIndicatorInd;
    }

    /**
     * private tariff indicator.
     *
     * @param string $privateTariffIndicatorInd
     *
     * @return self
     */
    public function setPrivateTariffIndicatorInd(?string $privateTariffIndicatorInd): self
    {
        $this->privateTariffIndicatorInd = $privateTariffIndicatorInd;

        return $this;
    }

    /**
     * Carrier code.
     *
     * @return string
     */
    public function getGoverningCarrier(): ?string
    {
        return $this->governingCarrier;
    }

    /**
     * Carrier code.
     *
     * @param string $governingCarrier
     *
     * @return self
     */
    public function setGoverningCarrier(?string $governingCarrier): self
    {
        $this->governingCarrier = $governingCarrier;

        return $this;
    }

    /**
     * fare type bitmap.
     *
     * @return string
     */
    public function getFareTypeBitmap(): ?string
    {
        return $this->fareTypeBitmap;
    }

    /**
     * fare type bitmap.
     *
     * @param string $fareTypeBitmap
     *
     * @return self
     */
    public function setFareTypeBitmap(?string $fareTypeBitmap): self
    {
        $this->fareTypeBitmap = $fareTypeBitmap;

        return $this;
    }

    /**
     * Fare type string.
     *
     * @return string
     */
    public function getFareType(): ?string
    {
        return $this->fareType;
    }

    /**
     * Fare type string.
     *
     * @param string $fareType
     *
     * @return self
     */
    public function setFareType(?string $fareType): self
    {
        $this->fareType = $fareType;

        return $this;
    }

    /**
     * fare indicator.
     *
     * @return string
     */
    public function getFareIndicator(): ?string
    {
        return $this->fareIndicator;
    }

    /**
     * fare indicator.
     *
     * @param string $fareIndicator
     *
     * @return self
     */
    public function setFareIndicator(?string $fareIndicator): self
    {
        $this->fareIndicator = $fareIndicator;

        return $this;
    }

    /**
     * Fare Component Identifier.
     *
     * @return string
     */
    public function getFareComponentID(): ?string
    {
        return $this->fareComponentID;
    }

    /**
     * Fare Component Identifier.
     *
     * @param string $fareComponentID
     *
     * @return self
     */
    public function setFareComponentID(?string $fareComponentID): self
    {
        $this->fareComponentID = $fareComponentID;

        return $this;
    }

    /**
     * Aptco fare tariff.
     *
     * @return string
     */
    public function getAtpcoFareTariff(): ?string
    {
        return $this->atpcoFareTariff;
    }

    /**
     * Aptco fare tariff.
     *
     * @param string $atpcoFareTariff
     *
     * @return self
     */
    public function setAtpcoFareTariff(?string $atpcoFareTariff): self
    {
        $this->atpcoFareTariff = $atpcoFareTariff;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getExtensionPointSummary()
    {
        return $this->extensionPointSummary;
    }

    /**
     * @param mixed $extensionPointSummary
     *
     * @return self
     */
    public function setExtensionPointSummary($extensionPointSummary): self
    {
        $this->extensionPointSummary = $extensionPointSummary;

        return $this;
    }
}
