<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\AdvancedCalendarSearch;

use Ammonkc\SabreApi\AbstractModel;

class AdvancedCalendarSearchResponse extends AbstractModel
{
    /**
     * @var AdvancedCalendarSearchResponseOTAAirLowFareSearchRS
     */
    protected $oTAAirLowFareSearchRS;
    /**
     * Array of links for different types of relations, e.g. self, linkTemplate, shop.
     *
     * @var AdvancedCalendarSearchResponseLinksItem[]
     */
    protected $links;
    /**
     * Array of page stats
     *
     * @var array
     */
    protected $page;

    /**
     * RequestID
     *
     * @var requestId
     */
    protected $requestId;

    /**
     * @return AdvancedCalendarSearchResponseOTAAirLowFareSearchRS
     */
    public function getOTAAirLowFareSearchRS(): ?AdvancedCalendarSearchResponseOTAAirLowFareSearchRS
    {
        return $this->oTAAirLowFareSearchRS;
    }

    /**
     * @param AdvancedCalendarSearchResponseOTAAirLowFareSearchRS $oTAAirLowFareSearchRS
     *
     * @return self
     */
    public function setOTAAirLowFareSearchRS(?AdvancedCalendarSearchResponseOTAAirLowFareSearchRS $oTAAirLowFareSearchRS): self
    {
        $this->oTAAirLowFareSearchRS = $oTAAirLowFareSearchRS;

        return $this;
    }

    /**
     * Array of links for different types of relations, e.g. self, linkTemplate, shop.
     *
     * @return AdvancedCalendarSearchResponseLinksItem[]
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * Array of links for different types of relations, e.g. self, linkTemplate, shop.
     *
     * @param AdvancedCalendarSearchResponseLinksItem[] $links
     *
     * @return self
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    /**
     * Array of page stats
     *
     * @return array
     */
    public function getPage(): ?array
    {
        return $this->page;
    }

    /**
     * Array of page stats
     *
     * @param array $page
     *
     * @return self
     */
    public function setPage(?array $page): self
    {
        $this->page = $page;

        return $this;
    }

    /**
     * RequestID
     *
     * @return requestId
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * RequestId
     *
     * @param string $requestId
     *
     * @return self
     */
    public function setRequestId($requestId): self
    {
        $this->requestId = $requestId;

        return $this;
    }

    /**
     * @return PricedItinerariesItem[]
     */
    public function getPricedItineraries()
    {
        return $this->oTAAirLowFareSearchRS->getPricedItineraries();
    }
}
