<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ammonkc\SabreApi\Model\AdvancedCalendarSearch;

use Ammonkc\SabreApi\AbstractModel;

class AdvancedCalendarSearchRequestOTAAirLowFareSearchRQTravelerInfoSummaryAirTravelerAvailItem extends AbstractModel
{
    /**
     * @var AdvancedCalendarSearchRequestOTAAirLowFareSearchRQTravelerInfoSummaryAirTravelerAvailItemPassengerTypeQuantityItem[]
     */
    protected $passengerTypeQuantity;

    /**
     * @return AdvancedCalendarSearchRequestOTAAirLowFareSearchRQTravelerInfoSummaryAirTravelerAvailItemPassengerTypeQuantityItem[]
     */
    public function getPassengerTypeQuantity(): ?array
    {
        return $this->passengerTypeQuantity;
    }

    /**
     * @param AdvancedCalendarSearchRequestOTAAirLowFareSearchRQTravelerInfoSummaryAirTravelerAvailItemPassengerTypeQuantityItem[] $passengerTypeQuantity
     *
     * @return self
     */
    public function setPassengerTypeQuantity(?array $passengerTypeQuantity): self
    {
        $this->passengerTypeQuantity = $passengerTypeQuantity;

        return $this;
    }
}
